---
- name: Add the deploy user
  user: name=deploy
        home=/home/deploy
        shell=/bin/bash
        comment="Deploy User"

- name: Enable sudo access for the deploy user
  user: name=deploy
        groups=sudo
        append=yes

- name: Set up authorized_keys for the deploy user
  authorized_key: user=deploy
                  state=present
                  key="{{ item }}"
  with_items:
    - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - "{{ lookup('file', '~/.ssh/id_dsa.pub') }}"
